### ISSUE TITLE
White background on wide screen.

### ISSUE THREAD

**Issue by sesm** [DudnovaP/webpage#2]
On large screen width user can see white background (see screenshot below). Consider stretching the background picture in this case.
![screen shot 2016-03-30 at 22 36 21](https://cloud.githubusercontent.com/assets/1313744/14154940/69f4206e-f6d0-11e5-8396-36d067749b98.png)

**Comment by DudnovaP** [comment]
fixed by commit "add video and db"

**Comment by sesm** [comment]
Please, add references to issues in your commit messages, for example 'fixes #2'
